### ISSUE TITLE
🐛 [bug] 가장 가까운 인프라 위치정보 오류

### ISSUE THREAD

**Issue by hyein99** [boostcampaitech4lv23recsys2/final-project-level3-recsys-10#34]
가장 가까운 infra_id와 거리(dist)가 다른 문제가 있습니다.

**Comment by Heiness** [comment]
[4a25f732] fix : Fix bug that insert incorrect infra_id
수정 내용 : 가장 가까운 인프라 id가 실제와 다른 문제 해결
