### ISSUE TITLE
🍀 [feat] 인프라 헬스장(08) 추가

### ISSUE THREAD

**Issue by hyein99** [boostcampaitech4lv23recsys2/final-project-level3-recsys-10#50]
- [x] INFRA 테이블 INSERT
- [x] INFRA_INFO 테이블 INSERT
- [x] GRID_SCORE 테이블 INSERT
- [x] 쿼리 추가

**Comment by dmscornjs** [comment]
INFRA 테이블 추가 완료했습니다.

**Comment by Heiness** [comment]
헬스장(08) INFRA_INFO 테이블 INSERT 완료했습니다.

**Comment by Heiness** [comment]
헬스장(08) GRID_SCORE  테이블 INSERT 완료했습니다.
