### ISSUE TITLE
🐛 [feat] 헬스장 인프라 추가, 공원 인프라 삭제

### ISSUE THREAD

**Issue by jhu8802** [boostcampaitech4lv23recsys2/final-project-level3-recsys-10#52]
기존 인프라 선택 페이지에서 공원 인프라는 삭제
헬스장 인프라 08번으로 추가 진행

**Comment by jhu8802** [comment]
![스크린샷 2023-01-31 오후 7 07 43](https://user-images.githubusercontent.com/65005242/215730526-b436b75d-5e63-44c0-bd09-de674b702edd.png)
기존 공원 인프라를 삭제하고 헬스장 인프라를 추가 하였습니다.

**Comment by jhu8802** [comment]
@hobbang2 안녕하세욥 config 파일 infra에 icon과, emoji 어떤 이미지와 아이콘을 쓰는줄 몰라
 icon과, emoji를 추가 가능할까욥,,
![스크린샷 2023-01-31 오후 7 10 08](https://user-images.githubusercontent.com/65005242/215731030-a3fa0ee4-5654-491e-ad43-0a3499d99143.png)

**Comment by hobbang2** [comment]
추가 완료했습니다 !
